### PR TITLE
feat!: build custom service worker using vite

### LINKED ISSUE #260: `injectManifest` doesn't include enough plugins
See #229 for an example of this - this plugin has a whitelist of allowed plugins when using `injectManifest`:

https://github.com/antfu/vite-plugin-pwa/blob/main/src/modules.ts#L41-L50

That issue needed at least `vite:asset` for it to work, possibly more.

I actually remember now debugging this about a year ago before abandoning this plugin and rolling my own to support my service worker setup. Your plugin is way, way, way better than mine :smile_cat: so I wanna get it working.

This works for me for the moment:

```diff
  const includedPluginNames = [
+   "commonjs",
+   "vite:asset",
+   "vite:json",
    "alias",
    "vite:resolve",
    "vite:esbuild",
    "replace",
    "vite:define",
    "rollup-plugin-dynamic-import-variables",
    "vite:esbuild-transpile",
    "vite:terser"
  ];
```
  
Honestly I am confused about this approach - I'm assuming there was a good reason to whitelist the plugins at some point, but I'm not seeing it. I'm also not that familiar with vite and rollup, so I don't really know the implications. In my hand-rolled plugin I just blacklisted my own plugin, and that worked fine. 
  
I see a few options really to solve this:

1. Just filter out `vite-plugin-pwa*`
2. Option 1 plus filtering out any known problem plugins from vite's default set.
3. Add a config option to easily add back plugins by name when needed.

I'd probably order them the same way as far as my preference of solution, I just don't know if the first one is feasible...although it's the easiest too.

In general though, users can use whatever plugins they want, and the whitelist feels like a pretty hostile approach - if you rely on any particular plugin for your service worker than you're out of luck here.

### PR DESCRIPTION
**Pull request by userquin**
I need to check PWA integrations, tested only with VitePress.

closes #260

### CODE REVIEW

**Comment by userquin** [comment]
This should be breaking, we're changing `injectManifest` behavior.

**Comment by AntonOfTheWoods** [comment]
As this is supposed to be a breaking change, is there a migration guide anywhere? Any pointers on what might break?

**Comment by userquin** [comment]
@AntonOfTheWoods the only change included is using vite in the build and the plugins entry, any plugin included should be added to plugins option, should not be reused.

Previous version reuse existing ones in vite config (by default using only vite internal plugins).

This PR use similar strategy to build webworkers in vite.

**Comment by AntonOfTheWoods** [comment]
@userquin  Thanks for your reply. I'm unavailable for the next couple of days but am not sure I understand anyway 😕, so not sure I'd be able to help with an example!

**Comment by doutatsu** [comment]
Same here - would like to understand better what could break and what I need to change in my configuration to make sure things work as expected

**Comment by userquin** [comment]
`0.14.7` version using `rollup` to build custom sw (rollup build plugins collecting vite plugins by name); from `0.15.0` you will need to add plugins twice, to your vite config file and in plugins option (for dev and build).

If you're not using any custom Vite plugin in your service worker, you don't need to change anything.

**Comment by doutatsu** [comment]
Does this mean I have to duplicate plugins in the vite config, into PWA? E.g. things like `VueI18nPlugin` would have to be added inside VitePWA options?
image

**Comment by userquin** [comment]
@doutatsu if you're using some vue-18n stuff inside the sw yes

**Comment by userquin** [comment]
@AntonOfTheWoods @laurentpayot  @doutatsu 

In dev mode it will work because we use type module and Vite will just remove TS anotations (esbuild) and the browser will resolve modules.

In build mode, reusing Vite plugins may fail or generate a weird sw code, it depends on the build type: for example, VitePress and SvelteKit generating weird sw build output (SSR build).

If you check Vite docs for WebWorkers (https://vitejs.dev/config/worker-options.html#worker-plugins), you need to do the same.

**Comment by laurentpayot** [comment]
Thanks @userquin for the precision. I added my plugins to  the `injectManifest.plugins` option and it works.

**Comment by doutatsu** [comment]
🤔 I don't actually do anything inside SW, I only use it to update the site, so I presume I don't need to do anything? Service Workers are still so confusing to me 😂 

```js
<script setup>
  import { useRegisterSW } from 'virtual:pwa-register/vue';

  const intervalMS = 1800000; // 30 minutes in milliseconds

  /* eslint-disable no-unused-vars */
  const { needRefresh, updateServiceWorker } = useRegisterSW({
    immediate: true,
    onRegistered(swUrl, r) {
      // eslint-disable-next-line no-unused-expressions
      r && setInterval(async () => {
        if (!(!r.installing && navigator)) { return; }
        if (('connection' in navigator) && !navigator.onLine) { return; }

        try {
          const response = await fetch(swUrl, {
            method: 'HEAD',
            cache: 'no-store',
            headers: { cache: 'no-store', 'cache-control': 'no-cache' },
          });

          if (response?.ok) { await r.update(); }
        } catch (_) { /* ignore */ }
      }, intervalMS);
    },
  });

  const close = async () => { needRefresh.value = false; };
  const updateWorker = async () => {
    close();
    updateServiceWorker();
  };
  /* eslint-enable */
</script>
```

**Pull request merged**
