### PR TITLE
chore: upgrade to latest eslint config

### PR DESCRIPTION
**Pull request by antfu**
The new config improves the consistent in quite many places

### CODE REVIEW

**Comment by userquin** [comment]
Running `nr examples` with vue router (default options):

imagen

**Comment by userquin** [comment]
Seems to be another problem, tsup preserving `process.node.NODE_ENV` in options module.

**Comment by antfu** [comment]
Oh that's unintentional, fixed

**Review by userquin — APPROVED** [review]
thx :tada:

**Review by userquin — APPROVED** [review]

**Pull request merged**
