### PR TITLE
fix: add manifestTransforms field in injectManifest option

### PR DESCRIPTION
**Pull request by tassioFront**
regarding [this issue](https://github.com/vite-pwa/vite-plugin-pwa/issues/504)

### CODE REVIEW

**Comment by tassioFront** [comment]
I''m getting this error on svelte examples, even before my changes.

Screen Shot 2023-04-27 at 21 15 06

**Review by mauriciomutte — APPROVED** [review]
LGTM

**Comment by userquin** [comment]
@tassioFront what are you doing with this PR? If you want to add a manifest transformer when using `strategies: 'injectManifest'` add it to `injectManifest` option instead `workbox` (`workbox` entry option is for strategies: 'generateSW').

**Comment by userquin** [comment]
imagen

**Comment by tassioFront** [comment]
@userquin, where can I find it on docs? Now I see it [here at the types file](https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/types.ts#L108-L115)

**Comment by userquin** [comment]
@tassioFront https://vite-pwa-org.netlify.app/workbox/

**Comment by tassioFront** [comment]
@userquin, thanks! Using `injectManifest` has worked as expected!

**Comment by userquin** [comment]
@tassioFront FYI: on a fresh clone I get your error, I solve it running `pnpm routify -b` from `examples/svelte-routify`, once `.routify` folder created, running again `pnpm examples` works (it seems we need to add `routify -b` to a few scripts):

imagen

**Comment by tassioFront** [comment]
@userquin, that works properly. Thanks! Does make sense to add it to the [CONTRIBUTING](https://github.com/vite-pwa/vite-plugin-pwa/blob/main/CONTRIBUTING.md) file?

**Comment by userquin** [comment]
@tassioFront I think there is no need, I have included a fix in my last draft PR, tmr I Will send a new one to fix it. 

Ppl using routify should deal with the library, we cannot include hints for every fw/lib here.

**Comment by tassioFront** [comment]
Right, @userquin. Thanks for your time!

**Pull request closed without merging**
