### PR TITLE
fix(dev): inject register not working when disabling web manifest

### LINKED ISSUE #660: InjectRegister not working when disabling manifest
Even though i set injectRegister as null still it is auto Registering. How do i stop it ?

### PR DESCRIPTION
**Pull request by userquin**
closes #660

### CODE REVIEW

**Comment by rschristian** [comment]
Gave this a quick test but it doesn't seem to correct the issue, unless I'm being daft (perfectly possible).

**Comment by userquin** [comment]
> Gave this a quick test but it doesn't seem to correct the issue, unless I'm being daft (perfectly possible).

I'm preparing some tests in my local, will take some time...

**Comment by rschristian** [comment]
No worries or rush! Just thought I'd comment that

**Comment by userquin** [comment]
I need to change also the `transformIndexHtml` in the dev plugin

**Comment by userquin** [comment]
> No worries or rush! Just thought I'd comment that

With last commit should work: tested with `vanilla-ts-dev-options` example.

**Pull request merged**
