### PR TITLE
fix: pwa assets disabled when using inlined configuration

### LINKED ISSUE #682: PWA Assets generation on the fly
``` plugins: [
    VitePWA({
      pwaAssets: {
        image: 'logo.png',
        includeHtmlHeadLinks: true,
        overrideManifestIcons: true
      },
    })
  ]
```

This config doesn't produce image files in build folder.
Please tell be what I doing wrong.

### PR DESCRIPTION
**Pull request by userquin**
closes #682

### CODE REVIEW

**Comment by real34** [comment]
@userquin We found that v0.19.3 introduced some regressions, and believe that it's this change that is the culprit. Icons aren't generated anymore because `disabled` resolves to `true` so the generator isn't loaded.

I'll work on a repro and open an issue next week, but wanted to notify sooner in case someone figures it before.

Here's a config that should allow to reproduce:
```js
      pwaAssets: {
        disabled: false,
        config: false,
        preset: {
		  transparent: {
		    sizes: [48, 72, 96, 144, 192, 256, 384, 512], // Comprehensive sizes for various Android devices
		    favicons: [
		      [16, "favicon-16x16.png"],
		      [32, "favicon-32x32.png"],
		      [48, "favicon.ico"],
		    ],
		  },
		  maskable: {
		    sizes: [192, 512], // Recommended sizes for maskable icons
		    padding: 0,
		  },
		  apple: {
		    sizes: [120, 152, 167, 180, 1024], // Covers iPad and iPhone touch icons plus one for the App Store
		  },
		},
        image: "public/favicon.svg",
        htmlPreset: "2023",
      },
```

**Comment by userquin** [comment]
can you try removing `config: false`?

**Comment by real34** [comment]
It's still the same.

**Comment by userquin** [comment]
can you file an issue? it is a bug, seems adding the preset sets the disable option to true :thinking:

**Comment by real34** [comment]
Sure. I'll do it early next week or this weekend, with a reproduction (or test case). I can't do it right now as I have to finalize a feature.

**Comment by userquin** [comment]
no need reproduction, I just copy/paste your configuration in the assets-generator example...

**Comment by userquin** [comment]
@real34 issue created, I'm going to release a new version in a few minutes.

**Comment by userquin** [comment]
@real34 released `v0.19.8` fixing the problem also including a fix about favicon preset, you can remove `htmlPreset: "2023",` from your configuration, the new version will use `2023` by default, check https://github.com/vite-pwa/vite-plugin-pwa/releases/tag/v0.19.8

**Comment by real34** [comment]
@userquin Thanks for this quick fix. It works like a charm!
I'll directly create a new issue next time :+1:

**Pull request merged**
